[package]
name = "tlsr8266_mesh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
lto = false
codegen-units = 1
panic = "abort"

[dependencies]
paste = "1.0"
const-cstr = "0.3"
keyframe = "1.1"
libm = "0.2"
externc-libm = "0.1.0"
embassy-time = { version = "0.1.0", features = ["tick-hz-32_000_000"] }
embassy-executor = { version = "0.1.1", features = ["nightly", "integrated-timers"] }
