[package]
name = "tlsr8266_mesh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
lto = false
#codegen-units = 1
panic = "abort"
strip = true

[dependencies]
paste = "1.0"
libm = "0.2"
embassy-time = { version = "0.1.0", features = ["tick-hz-32_000_000"] }
embassy-executor = { version = "0.1.1", features = ["nightly", "integrated-timers"] }
embassy-sync = "0.1.0"
heapless = "0.7"
critical-section = { version = "1.1", features = ["restore-state-u8"]}

[dependencies.easer]
version = "0.3"
default-features = false
features = ["libm"]
