[toolchain]
channel = "nightly-2025-03-30"                             #"nightly-2024-03-31"
components = ["rust-src", "rustc"]
targets = ["thumbv6m-none-eabi", "i686-unknown-linux-gnu"]
profile = "minimal"
